theme = "paper"
baseURL = "https://physicaladdons.com/blog/"
languageCode = "en-us"
title = "Blog"
author = "Physical Addons"
copyright = "Copyright © 2008–2019, Steve Francia and the lee.so; all rights reserved."

[params]
  color = 'linen'

  twitter = 'PhysicalAddons'
  github = 'PhysicalAddons'
  instagram = 'physicaladdons'

#  avatar = 'nanxiaobei@gmail.com'
  name = 'Physical Addons'
  bio = 'Discover physical properties of light and materials together with our R&D team.'


[menu]
  [[menu.main]]
    identifier = "documentation"
    name = "Documentation"
    url = "https://www.physicaladdons.com/psa/documentation"
    weight = 10
  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "https://www.physicaladdons.com/psa/"
    weight = 10
  